[package]
name = "detect"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Detection engine over socteam sensor events"

[lib]
name = "detect"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
sensor = { path = "../sensor" }

[dev-dependencies]
pnet.workspace = true
pnet_packet.workspace = true
hickory-proto.workspace = true
